all:
  children:
    managers:
      hosts:
        dockermanager:
      vars:
        ansible_user: jenkins
        ansible_ssh_private_key_file: '/home/jenkins/.ssh/ansible_id_rsa'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    workers:
      hosts:
        dockerworker:
      vars:
      ansible_user: jenkins
      ansible_ssh_private_key_file: '/home/jenkins/.ssh/ansible_id_rsa'
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        