all:
  children:
    managers:
      hosts:
        dockermanager:
    workers:
      hosts:
        dockerworker:
      vars:
        ansible_user: jenkins
        ansible_ssh_private_key_file: '/home/jenkins/.ssh/id_rsa.pub'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        