---
# tasks file for swarmworker

- name: "Add Worker to Swarm"
  docker_swarm:
    state: join
    advertise_addr: cards_against_humanity_worker
    join_token: "{{ hostvars['dockermanager']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'dockermanager:2377' ]